import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - Anchor',
  description: 'Terms of Service for Anchor',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen py-20 px-4" style={{ background: 'var(--anchor-base)' }}>
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-anchor-text-muted hover:text-anchor-text transition-colors mb-8"
        >
          ← Back to Home
        </Link>

        <h1 className="text-4xl font-bold text-anchor-text mb-4">TERMS OF SERVICE FOR ANCHOR</h1>
        <p className="text-sm text-anchor-text-muted mb-8">Effective Date: July 8, 2026</p>
        <p className="text-sm text-anchor-text-muted mb-6">Operating Entity: ClickBit | Applicable Jurisdiction: Commonwealth of Australia (Compliant with the Competition and Consumer Act 2010)</p>

        <div className="prose prose-invert max-w-none" style={{ color: 'var(--anchor-text-muted)' }}>
          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">1. ACCEPTANCE OF TERMS</h2>
          <p className="mb-4">These Terms of Service ("Terms") constitute a legally binding agreement between you and ClickBit ("we," "our," or "the Company"). By downloading, installing, or accessing the Anchor mobile application across iOS, iPadOS, or Android platforms, you agree to be legally bound by these Terms.</p>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">2. SERVICE DESCRIPTION</h2>
          <p className="mb-4">Anchor is a mobile productivity application designed specifically to facilitate routine management and habit tracking. The application provides tools, analytics, and integrations to organise and optimise your daily workflows.</p>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">3. ARTIFICIAL INTELLIGENCE AND FINANCIAL OPTIMISATION DISCLAIMER</h2>
          <p className="mb-4">Anchor incorporates an integrated AI agent powered by MiniMax to deliver personalised workflow insights and financial habit optimisations.</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>No Professional Advice:</strong> The insights and recommendations generated by the MiniMax AI agent regarding financial habits are strictly for informational and personal organisational purposes. ClickBit does not provide certified financial, legal, or investment advice.</li>
            <li><strong>User Responsibility:</strong> You maintain full responsibility for any financial, lifestyle, or business decisions made based on AI-generated suggestions.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">4. ACCOUNT CREATION AND FAMILY ACCOUNTS</h2>
          <p className="mb-4">To utilize Anchor, you must create a verified user account.</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Family Accounts:</strong> Anchor supports the creation and management of Family Accounts to share routines and tracking. The primary account holder must be at least 18 years of age and assumes full legal responsibility for all activity, data input, and usage generated by linked family members, including minors under their supervision.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">5. THIRD-PARTY INTEGRATIONS</h2>
          <p className="mb-4">Anchor allows you to connect and sync your routine data with external third-party services, explicitly including Clockify and Habitica.</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>External Terms:</strong> ClickBit is not responsible for the availability, data practices, or operational stability of Clockify, Habitica, or any other connected service. Your use of these third-party platforms is governed strictly by their respective Terms of Service and Privacy Policies.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">6. DATA PRIVACY AND ERASURE CONTROLS</h2>
          <p className="mb-4">Your privacy is governed by the ClickBit Enterprise Privacy & Data Governance Policy. Anchor is architected to strictly comply with the Privacy Act 1988 (Cth) and modern Australian privacy frameworks.</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Data Deletion:</strong> You retain complete control over your personal data. Anchor provides explicitly designed user privacy controls, including in-app mechanisms to request the complete deletion of your account and all associated telemetry and habit history.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">7. ACCEPTABLE USE</h2>
          <p className="mb-4">You agree not to use Anchor to:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Reverse-engineer, decompile, or attempt to extract the source code of the application or its AI agent models.</li>
            <li>Input malicious code, harmful scripts, or unlawful content into the routine trackers or AI prompt interfaces.</li>
            <li>Exploit the Family Account features to bypass subscription tiers or distribute the service commercially.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">8. REFUND POLICY AND CONSUMER GUARANTEES</h2>
          <p className="mb-4">Our digital services come with statutory guarantees that cannot be excluded under the Australian Consumer Law (ACL).</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Major Failures:</strong> For major failures with the Anchor service, you are entitled to cancel your service contract with ClickBit and receive a refund for the unused portion of your subscription, or to compensation for its reduced value.</li>
            <li><strong>Change of Mind:</strong> ClickBit does not provide refunds for a "change of mind" or for a failure to cancel a recurring subscription prior to the automated billing renewal date, except as strictly required by the ACL.</li>
            <li><strong>Marketplace Billing (App Store / Play Store):</strong> Because Anchor is distributed via mobile marketplaces, subscriptions and in-app purchases processed directly through Apple (App Store) or Google (Play Store) are subject to the refund policies and processing mechanisms of those respective platforms. You must initiate refund requests for these transactions directly through your Apple ID or Google Play account.</li>
          </ul>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">9. LIMITATION OF LIABILITY</h2>
          <p className="mb-4">To the maximum extent permitted by the Australian Consumer Law, ClickBit shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of Anchor. ClickBit provides the platform "as-is" and does not warrant that the application will be entirely error-free or that the MiniMax AI agent will provide flawless or perfectly accurate optimizations.</p>

          <h2 className="text-2xl font-semibold text-anchor-text mt-8 mb-4">10. GOVERNING LAW</h2>
          <p className="mb-4">These Terms are governed by the laws of the Commonwealth of Australia. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the Australian federal and state courts.</p>
        </div>
      </div>
    </div>
  );
}
